- name: Run the equivalent of "pacman -Syu"
  pacman:
    update_cache: yes
    upgrade: yes

  - name: Install list of packages
    pacman:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - arandr
        - bat
        - cmatrix
        - couchdb
        - git
        - postgresql
        - terminator
        - thunderbird
        - tor
        - tmux
        - unrar
        - unzip
        - vim
        - xclip
        - xorg-apps
        - youtube-dl
        - zsh

  - name: Upgrade all packages to the latest version
    pacman:
      update_cache: yes
      upgrade: yes