- name: Run the equivalent of "pacman -Syu"
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install list of pacman packages
  pacman:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
      - arandr
      - bat
      - cmatrix
      - couchdb
      - git
      - jre10-openjdk
      - neofetch
      - pavucontrol
      - pulseaudio
      - postgresql
      - ranger
      - redshift
      - steam
      - terminator
      - thunderbird
      - tor
      - tmux
      - unrar
      - unzip
      - vim
      - xclip
      - xorg-apps
      - youtube-dl
      - yay
      - zsh

- name: Upgrade all packages to the latest version
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes
