- name: Remove current .Xresources file
  file:
    dest: "/home/olo2552/.Xresources"
    state: absent

- name: Create symbolic link with versioned file
  file:
    src: "/home/olo2552/repos/REVIVE/.Xresources"
    dest: "/home/olo2552/.Xresources"
    state: link
    force: yes
