---
- name: Revive the localhost system
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Print out the hostname of target
      command: hostname
  roles:
    # - nopasswd
    # - oh-my-zsh
    # - keepass
    # - pacman
    # - aliases
    # - redshift
    # - yaourt
    # - dpi
    # - locale
    # - docker
    - nvim