---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Print out the hostname of target
      command: hostname
  
  roles:
    - oh-my-zsh
    - keepass
    - pacman