---
- name: Revive the localhost system
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Print out the hostname of target
      command: hostname
  roles:
    # - pacman
    # - yaourt
    # - stow
    # - nopasswd
    # - oh-my-zsh
    # - keepass
  # - locale
    # - docker
  # - nvim
    - swapoff
  #- githubixx.kubectl
