- name: Get .bashrc stat to be able to perform a backup
  stat:
    path: $SUDO_USER/.zshrc
  register: zshrc

- name: Backup existing ~/.zshrc
  copy:
    src: $SUDO_USER/.zshrc
    dest: $SUDO_USER/.zshrc_backup
  become: no
  when: zshrc.stat.exists

- name: Create symbolic link for versioned .bash_aliases
  file:
    src: "/home/$SUDO_USER/repos/REVIVE/.bash_aliases"
    dest: "/home/$SUDO_USER/.bash_aliases"
    state: link

- name: Source bash_aliases to .zshrc for Z-shell support
  lineinfile:
    dest: ~/.zshrc
    line: "source ~/.bash_aliases"
    regexp: "^source*bash_aliases"
    owner: "{{ ansible_user_id }}"
    state: present
    insertafter: EOF
    create: yes