---
- name: Install KeePassX
  pacman:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - keepassxc

- name: Cloning KeePassDB
  git:
    repo: https://github.com/olo2552/keepassDB.git
    dest: ~/repos/keepassDB
    clone: yes
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
