---
- name: Install KeePassX
  pacman:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - keepassx

- name: Cloning KeePassDB
  git:
    repo: https://github.com/olo2552/keepassDB.git
    dest: ~/repos/keepassDB
    clone: yes
