---
- name: Install Z-Shell
  pacman:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - zsh
  become: yes 

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/tatchy/.oh-my-zsh
    clone: yes
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"

- name: Download ZSH autocompletion
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/tatchy/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"

- name: Install aterminal plugin
  shell: "bash < <(curl -s -S -L https://raw.githubusercontent.com/guiferpa/aterminal/master/installer.sh)"
  ignore_errors: true
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"

- name: Change default shell to ZSH
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
  become: yes
