---
- name: Install Z-Shell
  pacman:
    state: latest
    name: "{{ packages }}"
    register: installation
  variables:
    packages:
      - git
      - zsh

- name: Backing up existing ~/.zshrc
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc.backup
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
  when: installation == success
  become: no

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation == success
  register: cloning
  become: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning == success
  become: no
