---
- name: Install Z-Shell
  pacman:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - zsh
  become: yes 

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    clone: yes

- name: Change default shell to ZSH
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: yes

- name: Download ZSH autocompletion
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/olo2552/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes

- name: Create symbolic link for versioned .zshrc
  file:
    src: "/home/olo2552/repos/REVIVE/.zshrc"
    dest: "/home/olo2552/.zshrc"
    state: link
    force: yes