---
- name: Install Z-Shell
  pacman:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - zsh

- name: Get .zshrc stat to be able to perform a backup
  stat:
    path: ~/.zshrc
  register: zshrc

- name: Backing up existing ~/.zshrc
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc_backup
  become: no
  when: zshrc.stat.exists

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  register: cloning
  become: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning is success
  become: no
