---
- name: Manually install ansible-aur-git
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: /home/tatchy/.ansible/plugins/modules/aur
    clone: yes
  become: yes
  # become_user: "{{ lookup('env', 'USER') }}"

- name: Install yaourt packages
  aur: 
    use: yay
    aur_only: no
    skip_pgp_check: no
    name: 
      - google-chrome
      - jetbrains-toolbox
      - keeweb
      - ngrok
      - slack-desktop
      - spotify
  become_user: "{{ lookup('env', 'USER') }}"
