# - name: Ensure NeoVim is installed
#   pacman:
#     name: "{{ packages }}"
#     state: latest
#   become: yes
#   vars:
#     packages:
#       - python
#       - python3
#       - python-pip
#       - neovim

- name: Ensure folder for VimPlug Exists
  file: 
    path: "/home/{{ lookup('env', 'USER') }}/.local/share/nvim/site/autoload/"
    recurse: yes
    state: directory
  become_user: "{{ lookup('env', 'USER') }}"

- name: Install VimPlug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ lookup('env', 'USER') }}/.local/share/nvim/site/autoload/plug.vim"
    force: yes
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"

- name: install YouCompleteMe deps
  pip:
    name: neovim